# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_page_url', models.CharField(max_length=250, null=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='from_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_page', to='cyoa_app.Page'),
        ),
        migrations.AddField(
            model_name='choice',
            name='to_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_page', to='cyoa_app.Page'),
        ),
    ]
